apiVersion: tekton.dev/v1beta1 
kind: Task 
metadata: 
  name: deploy-yaml 
  namespace: tekton-pipelines 
spec: 
  params: 
    - default: '' 
      description: yamlfile alocated in the bastion host 
      name: yamlfile 
      type: string 
  steps: 
    - args: 
        - '-c' 
        - oc apply -f $(params.yamlfile) 
      command: 
        - /bin/bash 
      image: 'BastionOp.lab.azure:5000/clientes/clientes' 
      name: date 
